services:
  user_service:
    build:
      context: .
      dockerfile: agarthan/user_service/Dockerfile
    environment:
      DB_DSN: host=postgres user=postgres password=postgres dbname=agarthan port=5432 sslmode=disable
    depends_on:
      - postgres
    networks:
      - app_net

  report_service:
    build:
      context: .
      dockerfile: agarthan/report_service/Dockerfile
    environment:
      DB_DSN: host=postgres user=postgres password=postgres dbname=agarthan port=5432 sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
          condition: service_healthy
    networks:
      - app_net

  search_service:
    build:
      context: .
      dockerfile: agarthan/search_service/Dockerfile
    environment:
      DB_DSN: host=postgres user=postgres password=postgres dbname=agarthan port=5432 sslmode=disable
      READ_DB_DSN: host=postgres user=postgres password=postgres dbname=agarthan port=5432 sslmode=disable
      OPENSEARCH_URL: http://opensearch:9200
      OPENSEARCH_INDEX: reports
    depends_on:
      postgres:
        condition: service_healthy
      opensearch:
        condition: service_started
    networks:
      - app_net

  auth_service:
    build:
      context: .
      dockerfile: agarthan/auth_service/Dockerfile
    environment:
      DB_DSN: host=postgres user=postgres password=postgres dbname=agarthan port=5432 sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_net

  report_worker:
    build:
      context: .
      dockerfile: agarthan/report_worker/Dockerfile
    environment:
      DB_DSN: host=postgres user=postgres password=postgres dbname=agarthan port=5432 sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      KAFKA_BROKERS: kafka:19092
      KAFKA_TOPIC: submission.events
      KAFKA_REPORT_PUBLISHED_TOPIC: report.published
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app_net

  workforce_rotation:
    build:
      context: .
      dockerfile: agarthan/workforce_rotation/Dockerfile
    environment:
      DB_DSN: host=postgres user=postgres password=postgres dbname=agarthan port=5432 sslmode=disable
      KAFKA_BROKERS: kafka:19092
      KAFKA_REPORT_PUBLISHED_TOPIC: report.published
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - app_net

  report_sync_service:
    build:
      context: .
      dockerfile: agarthan/report_sync_service/Dockerfile
    environment:
      DB_DSN: host=postgres user=postgres password=postgres dbname=agarthan port=5432 sslmode=disable
      OPENSEARCH_URL: http://opensearch:9200
      OPENSEARCH_INDEX: reports
      SYNC_INTERVAL: 30s
    depends_on:
      postgres:
        condition: service_healthy
      opensearch:
        condition: service_started
    networks:
      - app_net

  notification_service:
    build:
      context: .
      dockerfile: agarthan/notification_service/Dockerfile
    environment:
      KAFKA_BROKERS: kafka:19092
      KAFKA_TOPIC: submission.events
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app_net

  api_gateway:
    image: nginx:1.27-alpine
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    # depends_on:
    #   - auth_service
    #   - user_service
    #   - report_service
    #   - search_service
    #   - notification_service
    #   - frontend
    networks:
      - app_net
    ports:
      - "8080:80"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3005:3005"
    networks:
      - app_net

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      # https://www.rabbitmq.com/docs/monitoring#stage-3
      test: rabbitmq-diagnostics --quiet check_running && rabbitmq-diagnostics --quiet check_local_alarms
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  kafka:
    build:
      context: .
      dockerfile: services/kafka/Dockerfile
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
      KAFKA_INTER_BROKER_PROTOCOL_VERSION: "3.7"
      KAFKA_LOG_MESSAGE_FORMAT_VERSION: "3.7"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app_net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: agarthan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agarthan"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app_net

  opensearch:
    image: opensearchproject/opensearch:3.4.0
    container_name: opensearch
    environment:
      discovery.type: single-node
      node.name: opensearch
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      DISABLE_INSTALL_DEMO_CONFIG: true # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      DISABLE_SECURITY_PLUGIN: true
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - app_net

volumes:
  postgres_data:
  opensearch-data:

networks:
  app_net:
